version: '1'

services:
  postgres:
    image: postgres
    container_name: kadocms-postgres
    ports:
      - '54327:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-kadocms
    volumes:
      - data_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: kadocms-redis
    ports:
      - '63797:6379'
    volumes:
      - data_redis:/data

volumes:
  data_postgres:
  data_redis:
